; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.11886.00 

	TITLE	C:\Users\S7Clutch\Documents\Visual Studio 2010\Projects\The Saiyan Project\src\stdafx.cpp
	.PPC
	.MODEL FLAT
END
